import 'package:flutter/material.dart';
import 'package:share_near/src/utils/size_config.dart';

const Color primaryColor = Color(0xFF2D365C);
const secondaryColor = Color(0xFF979797);
const textColor = Color(0xFF757575);
SizedBox littleGap = SizedBox(height: SizeConfig.screenHeight * 0.02);
SizedBox smallerGap = SizedBox(height: SizeConfig.screenHeight * 0.04);
SizedBox biggerGap = SizedBox(height: SizeConfig.screenHeight * 0.08);

String? appUserEmail;

List<String> bangladeshDistricts = [
  'Bagerhat',
  'Bandarban',
  'Barguna',
  'Barisal',
  'Bhola',
  'Bogra',
  'Brahmanbaria',
  'Chandpur',
  'Chapainawabganj',
  'Chittagong',
  'Chuadanga',
  'Comilla',
  'Cox\'s Bazar',
  'Dhaka',
  'Dinajpur',
  'Faridpur',
  'Feni',
  'Gaibandha',
  'Gazipur',
  'Gopalganj',
  'Habiganj',
  'Jaipurhat',
  'Jamalpur',
  'Jessore',
  'Jhalokati',
  'Jhenaidah',
  'Joypurhat',
  'Khagrachari',
  'Khulna',
  'Kishoreganj',
  'Kurigram',
  'Kushtia',
  'Lakshmipur',
  'Lalmonirhat',
  'Madaripur',
  'Magura',
  'Manikganj',
  'Meherpur',
  'Moulvibazar',
  'Munshiganj',
  'Mymensingh',
  'Naogaon',
  'Narail',
  'Narayanganj',
  'Narsingdi',
  'Natore',
  'Netrokona',
  'Nilphamari',
  'Noakhali',
  'Pabna',
  'Panchagarh',
  'Patuakhali',
  'Pirojpur',
  'Rajbari',
  'Rajshahi',
  'Rangamati',
  'Rangpur',
  'Satkhira',
  'Shariatpur',
  'Sherpur',
  'Sirajganj',
  'Sunamganj',
  'Sylhet',
  'Tangail',
  'Thakurgaon',
];
