// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoKYvfW90HGgHQMuTN3Yib4onK6XV6RGg',
    appId: '1:900440514087:web:c260f3e87d3f38155f3802',
    messagingSenderId: '900440514087',
    projectId: 'flutter-muaz',
    authDomain: 'flutter-muaz.firebaseapp.com',
    storageBucket: 'flutter-muaz.appspot.com',
    measurementId: 'G-9F6EZ3NJKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQuAmHBTSQd9QNE8LeJh5imSzksf5XBs8',
    appId: '1:900440514087:android:cd6d990be76a16eb5f3802',
    messagingSenderId: '900440514087',
    projectId: 'flutter-muaz',
    storageBucket: 'flutter-muaz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWSk2g7RIMPNRWn6b5wsECPpYquHv_HOg',
    appId: '1:900440514087:ios:9165425eb00e94b85f3802',
    messagingSenderId: '900440514087',
    projectId: 'flutter-muaz',
    storageBucket: 'flutter-muaz.appspot.com',
    iosClientId: '900440514087-558uo3lc981f19dj079iofmusnatdfo2.apps.googleusercontent.com',
    iosBundleId: 'com.teamone.shareNear',
  );
}
